---
- name: Create Oracle User
  hosts: localhost
  vars:
   oport: "1521"
   odtbsp: "USERS"
   ottbsp: "TEMP"
   profiles:
     BusinessUser:
       user_profile: BUSINESS_PROFILE
     Developer:
       user_profile: DEV_PROFILE
     DataArchitect:
       user_profile: DA_PROFILE
     DBA:
       user_profile: DBA_PROFILE
   ostate: "present"
   pii: "NO"
   pci: "NO"
   new_passwd: "{{ lookup('password','/dev/null length=16') }}"

  tasks:
   - name: Create the new Oracle user password
     set_fact:
       oschemapwd: "\"{{ new_passwd }}\""
     no_log: true

   - name: Debug block
     debug:
       msg: "DEBUG: oschemapwd = [{{ oschemapwd }}]"

   - name: Create the user
     oracle_user:
       hostname: "{{ ohost }}"
       service_name: "{{ oservice }}"
       user: "{{ ouser }}"
       password: "{{ opw }}"
       port: "{{ oport }}"
       schema: "{{ oschema }}"
       schema_password: "{{ oschemapwd }}"
       #schema_password: "{{ lookup('password','/dev/null length=16') }}"
       default_tablespace: "{{ odtbsp }}"
       default_temp_tablespace: "{{ ottbsp }}"
       profile: "{{ profiles[oprofile]['user_profile'] }}"
     register: sqluser
   - debug:
       var: sqluser

   - name: Grant basic privs to user
     oracle_grants:
       hostname: "{{ ohost }}"
       service_name: "{{ oservice }}"
       user: "{{ ouser }}"
       password: "{{ opw }}"
       port: "{{ oport }}"
       schema: "{{ oschema }}"
       grants_mode: "append"
       grants: "READ_NON_SENSITIVE_ROLE"
     register: sqlgrant
   - debug:
       var: sqlgrant

   - name: Grant pii privs to user
     oracle_grants:
       hostname: "{{ ohost }}"
       service_name: "{{ oservice }}"
       user: "{{ ouser }}"
       password: "{{ opw }}"
       port: "{{ oport }}"
       schema: "{{ oschema }}"
       grants_mode: "append"
       grants: "READ_PII_ROLE"
     when: pii == "YES"
     register: piigrant
   - debug:
       var: piigrant

   - name: Grant pci privs to user
     oracle_grants:
       hostname: "{{ ohost }}"
       service_name: "{{ oservice }}"
       user: "{{ ouser }}"
       password: "{{ opw }}"
       port: "{{ oport }}"
       schema: "{{ oschema }}"
       grants_mode: "append"
       grants: "READ_PCI_ROLE"
     when: pci == "YES"
     register: pcigrant
   - debug:
       var: pcigrant
